### ISSUE TITLE
I'd like to make some pages for a few mods I have

### ISSUE THREAD

**Issue by katubug** [Lykrast/UniversalBestiary#10]
Hi! I'd like to include this in a pack I'm working on, but some of the mobs are not yet included in the mods supported by UB. I am familiar with editing Patchouli books, and I see that you have some templates in the source, so I thought perhaps I'd just do them myself, and then I could submit a PR, if you're interested?

However, I wanted to check with you before I got started, to a) see if you'd be interested in some help, and b) to make sure I understand how best to use the templates you have uploaded. I'm not familiar with executing python scripts, so if you have a tutorial, I wouldn't mind trying to learn. Otherwise, I can just do them by hand, it's not a big deal either way.

Let me know! Thanks very much :)

Oh - the mods I wanted to make support for are:
- Beasts by Coda1552 (this is a maybe - it depends on whether or not the mod gets updated to fix a crash with my modpack)
- Deadly Monsters by radoslawg
- Eyes in the Darkness by gigaherz (another maybe - they can't be "killed" and they cannot kill the player)
- Fish's Undead Rising by fish0016054
- Mowzie's Mobs by bobmowzie
- Mutant Beasts by Chumbanotz
- Project: Vibrant Journeys by solis_nova123
- Sanity by tiffit_ (again a maybe - same issues as Eyes in the Darkness)
- Better With Mods by primetoxins

**Comment by tyon2006** [comment]
Hey, it's been a while. Sorry about that :D

I'm looking for help on doing quite a lot of entries. I just updated the mod for the first time in a while, just checking in to see if you're still interested in helping?

**Comment by katubug** [comment]
Hi! Sorry, I'm not really playing much these days, anymore. But I hope you can find someone to help out!
