### ISSUE TITLE
Change Yuki_Onna to Yuki-Onna?

### ISSUE THREAD

**Issue by Blueberryy** [Lykrast/UniversalBestiary#19]
Please?
https://github.com/Lykrast/UniversalBestiary/blob/85df4f07d4522dac825687aabd78b49e4acfb98c/src/main/resources/assets/universalbestiary/patchouli_books/bestiary/en_us/entries/grimoireofgaia_yuki_onna.json#L2

**Comment by tyon2006** [comment]
Fixed in code, will appear in next release.
