### ISSUE TITLE
Change WitherCow to Wither Cow

### ISSUE THREAD

**Issue by Blueberryy** [Lykrast/UniversalBestiary#20]
https://github.com/Lykrast/UniversalBestiary/blob/85df4f07d4522dac825687aabd78b49e4acfb98c/src/main/resources/assets/universalbestiary/patchouli_books/bestiary/en_us/entries/grimoireofgaia_wither_cow.json#L2

**Comment by tyon2006** [comment]
Fixed in the code now, will be fixed in next version. Thanks!
